### ISSUE TITLE
Creating management user via UI is not suitable for Containerization

### ISSUE THREAD

**Issue by ygokirmak** [hazelcast/management-center-docker#1]
Hi,

We are using hazelcast/management-center docker image but when container is started we need to create a user for login.

This user should be configured via env variables..

Is it supported? If not I can try my best to contribute..

**Comment by LMalikov** [comment]
+1 on this.

Also would be great to have an option to disable login layer at all for the container since security is most likely handled outside of it already (e.g. we have google IAP in front of our cluster).

**Comment by dbrimley** [comment]
+1 on this feature, we'll add it to the roadmap.

@LMalikov If you disabled security on the Management Centre as you request, how would you intend to allocate the required MC roles such as read-only, admin and metrics?

**Comment by ps-jay** [comment]
I'd like a non-GUI way to install an Enterprise license key, that's for sure.

At the moment, we have to do this after starting the container:

```
curl -k -H 'Content-Type: application/x-www-form-urlencoded' -X POST http://localhost:8080/mancenter/main.do?operation=savelicense -d "key=${LIC}" -b cookies.file
```

**Comment by emre-aydin** [comment]
@ps-jay this is added recently, please see this section for details: https://github.com/hazelcast/management-center-docker#mounting-management-center-home-directory

**Comment by ps-jay** [comment]
Ah!  Nice one. 

I missed it as I was reading the 3.9-EA doco. 
Oops.

**Comment by emre-aydin** [comment]
@ps-jay it is a per-cluster setting, but it might be useful to have a flag to turn it on by default for all clusters (or maybe per cluster by providing cluster names). We will introduce a configuration file in the near future, it might be an option there. It will also have variable replacement functionality, so you will be able to use system properties for all the configuration options you'd like. Can you create a separate issue for this?

**Comment by ps-jay** [comment]
I haven't observed it being a per-cluster setting ...  but is that because of the bug reported in Hazelcast Zendesk ticket 4024 ?

But yes, it would be good for us to be able to default that setting on, for all clusters.

**Comment by emre-aydin** [comment]
Ah sorry, you're right, it's not enabled per-cluster. I probably remember a feature request to do it so.

**Comment by puzpuzpuz** [comment]
A late update, but still. MC 3.12 adds [MC Conf](https://docs.hazelcast.org/docs/management-center/3.12/manual/html/index.html#mc-conf) command-line tool that includes user management commands. With this new tool it's now possible to build a Docker image with predefined users accounts:
https://github.com/hazelcast/hazelcast-docker-samples/tree/master/management-center-built-in-user

**Comment by scoopex** [comment]
> A late update, but still. MC 3.12 adds [MC Conf](https://docs.hazelcast.org/docs/management-center/3.12/manual/html/index.html#mc-conf) command-line tool that includes user management commands. With this new tool it's now possible to build a Docker image with predefined users accounts:
> https://github.com/hazelcast/hazelcast-docker-samples/tree/master/management-center-built-in-user

Thats good. I created a pull request which ads the possibility to execute commands or scripts on container startup.
https://github.com/hazelcast/management-center-docker/pull/19

**Comment by puzpuzpuz** [comment]
@scoopex That's a nice addition. Many thanks for contributing!

cc @emre-aydin

**Comment by scoopex** [comment]
You can close this issue now :-)

**Comment by puzpuzpuz** [comment]
@scoopex thanks for the reminder. Closing it now :)

And once again, many thanks for the contribution!
