### ISSUE TITLE
Use -XX:+UseCGroupMemoryLimitForHeap instead of Xms/Xmx?

### ISSUE THREAD

**Issue by rmannibucau** [hazelcast/management-center-docker#11]
Hi, any reason to not use -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap to reuse the container memory for the JVM?

**Comment by JackPGreen** [comment]
[`management-center` now uses `MaxRAMPercentage`](https://github.com/hazelcast/management-center/blob/c026204898e88a69ba3e06edd9ff700e418c8c80/hazelcast-management-center-distribution/src/bin/0755/hz-mc#L87).
