### ISSUE TITLE
Consider including client discovery plugins into MC 4.0+ image

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/management-center-docker#22]
Many users may want to run containerized MC 4.0 in Kubernetes or other environments (say, AWS). At the moment MC 4.0 uses base IMDG artifact and which lacks plugins like [the k8s one](https://github.com/hazelcast/hazelcast-kubernetes). We should consider including plugins into the image (i.e. into `MC_CLASSPATH`) by the default.

To give more context, here is a primitive image that is built on top of MC image and includes k8s plugin:
```
FROM hazelcast/management-center:4.0

RUN wget -O ${MC_HOME}/hazelcast-kubernetes.jar \
          https://repo1.maven.org/maven2/com/hazelcast/hazelcast-kubernetes/2.0.1/hazelcast-kubernetes-2.0.1.jar

ENV MC_CLASSPATH "${MC_HOME}/hazelcast-kubernetes.jar"

CMD ["bash", "/mc-start.sh"]
```

cc @emre-aydin

**Comment by emre-aydin** [comment]
Seems like a good idea to me. We can include AWS plugin as well and add instructions on how to start on those enviroments.

**Comment by puzpuzpuz** [comment]
Note. MC 4.1+ will start using Jet EE as the dependency, which means that MC .jar will include discovery plugins.

**Comment by emre-aydin** [comment]
I have verified that the MC 4.1 image will contain the discovery plugins as expected since they are already contained in the Jet EE JAR.
