### ISSUE TITLE
Add MC_ADMIN_USER and MC_ADMIN_PASSWORD environment variables

### ISSUE THREAD

**Issue by emre-aydin** [hazelcast/management-center-docker#26]
When these two are present, we will create the default admin user with the specified credentials before container start. 

~We might also consider creating a default user named `admin` with an auto-generated password that's printed to the console during container start when these two variables are not present.~ -> this will not be necessary, as we will add a no-op security provider to MC soon.

See [this PR](https://github.com/hazelcast/charts/pull/77) for the background discussion.

**Comment by cristina-sirbu** [comment]
Can I take this issue? 😄

**Comment by emre-aydin** [comment]
Hi @cristina-sirbu, sure and thanks for helping out! Let us know if you need any help or have any questions.

**Comment by mesutcelik** [comment]
@cristina-sirbu Thanks for taking over it. 

This was a blocker for  https://github.com/hazelcast/charts/pull/77
