### ISSUE TITLE
Setting up security provider AD with mc-conf.sh fails

### ISSUE THREAD

**Issue by jamjon3** [hazelcast/management-center-docker#86]
I've been struggling with this as it's not well documented mc-conf with useful examples. Nothing I seems to get this configured for AD. I got desperate and tried to set it to 'Dev Mode' so I could just handle it manually though the gui and still no go.

I am working with 4.2021.03

For that, I tried passing this into the container

MC_INIT_CMD=./bin/mc-conf.sh security reset && ./bin/mc-conf.sh dev-mode configure

The point is to go back and configure it for AD. In 3.x, I used a security.properties and ldap.properties to handle this in automation. That doesn't appear to do anything and the provider is stuck on default. 

I've passed the mc-conf.sh active-directory configure <plus options> and still stuck on provider default.

Is there a 'best way' handled setting up active-directory via automation? I'm OK with handling this in the Dockerfile (saw an example).

Note: I even tried the /data/import/securityHotReload.properties and that never comes up on the login (to reload)

Does this even work at all? Some working example somewhere? Help!

**Comment by emre-aydin** [comment]
Hi @jamjon3,

The properties in the file you mentioned for 3.x correspond to the options we have in `mc-conf.sh`. This is just a new way of doing the same thing that lets us do this security configuration dynamic. Doing it manually via the UI is the same. There should be no difference. 

To set up Active Directory integration, you don't need to first set up Dev Mode and then update. You can directly configure it on first start of the Management Center. AFAICT this also doesn't work for you, is this right? If that's the case, there's probably either a configuration error on your side or a bug on our Active Directory integration (which means it's not specific to `mc-conf.sh`).

Do you have any logs either from the Management Center or your Active Directory server that might help us debug the problem?

It's a good idea to add some sample mc-conf commands to the documentation. I will create an issue for this in our internal issue tracker.

**Comment by jamjon3** [comment]
You're correct that it didn't work for me. 

I'd prefer to have it working on the first start if I could get it to stick (and not just show the 'default'). If I could get something more concrete as an example, it would be a better place to debug from there (or it just works). This may just 'work' for me that will save you reviewing logs (I'm handling that via journald).

I'm not wedded to anything I was attempting but showing me an example of 'first start' setup it the preferred way forward.

Note: I have AD groups with spaces in there and that stuff was escaped in 3.x (fyi: if special handling is required for 4.x).

**Comment by emre-aydin** [comment]
Hi @jamjon3,

See the following example that starts a Management Center instance with Active Directory pre-configured:

```
docker run --name hazelcast-mc -p 8080:8080 \
  --env "MC_INIT_CMD=./bin/mc-conf.sh active-directory configure --url=ldap://54.87.55.160:389 --domain=aydin.tech --admin-groups=theAdminGroup --read-write-groups=c --read-only-groups=a --metrics-only-groups=b --user-search-filter='(&(objectClass=user)(userPrincipalName={0}))'" \
  --rm hazelcast/management-center:4.2021.06
```

You need to have single quotes around the group names if they contain spaces in them. Let me know if that helps.

**Comment by jamjon3** [comment]
Just closing this. Works great! Thank you!
